name: DereCounter
author: DereWah
description: A plugin to add registers and counters in minecraft.
version: 1.1
api-version: 1.13
main: org.derewah.derecounter.DereCounter
commands:
  derecounter:
    description: Base command.